import logo from "../assets/images/nxg-logo.png";
export const users = [
  {
    id: "0",
    email: "jack@gmail.com",
    firstName: "John",
    lastName: "Doe",
    phoneNumber: "0809845732",
    schoolOrOrganisation: "Next gen hub",
    hasLaptop: true,
    hasProgrammingExperience: true,
    availableHoursPerWeek: 5,
    hasWorkExperience: true,
    cvUrl: "string",
    registrationDate: "2024-10-11T18:07:08.369Z",
    passportUrl: logo,
    motivation: "Career Growth",
    preferredStack: "Software Development",
    duration: "6 Months",
    referralSource: "Linkedin",
    transferStatus: "Successful",
    transferReceiptUrl: "string",
  },
  {
    id: "1",
    email: "kenesongodwin@gmail.com",
    firstName: "John",
    lastName: "Doe",
    phoneNumber: "0809845732",
    schoolOrOrganisation: "Next gen hub",
    hasLaptop: true,
    hasProgrammingExperience: true,
    availableHoursPerWeek: 5,
    hasWorkExperience: true,
    cvUrl: "string",
    registrationDate: "2024-10-11T18:07:08.369Z",
    passportUrl: logo,
    motivation: "Career Growth",
    preferredStack: "Software Development",
    duration: "6 Months",
    referralSource: "Linkedin",
    transferStatus: "Successful",
    transferReceiptUrl: "string",
  },
  {
    id: "2",
    email: "jack@gmail.com",
    firstName: "John",
    lastName: "Doe",
    phoneNumber: "0809845732",
    schoolOrOrganisation: "Next gen hub",
    hasLaptop: true,
    hasProgrammingExperience: true,
    availableHoursPerWeek: 5,
    hasWorkExperience: true,
    cvUrl: "string",
    registrationDate: "2024-10-11T18:07:08.369Z",
    passportUrl: logo,
    motivation: "Career Growth",
    preferredStack: "Software Development",
    duration: "6 Months",
    referralSource: "Linkedin",
    transferStatus: "Successful",
    transferReceiptUrl: "string",
  },
  {
    id: "3",
    email: "jack@gmail.com",
    firstName: "John",
    lastName: "Doe",
    phoneNumber: "0809845732",
    schoolOrOrganisation: "Next gen hub",
    hasLaptop: true,
    hasProgrammingExperience: true,
    availableHoursPerWeek: 5,
    hasWorkExperience: true,
    cvUrl: "string",
    registrationDate: "2024-10-11T18:07:08.369Z",
    passportUrl: logo,
    motivation: "Career Growth",
    preferredStack: "Software Development",
    duration: "6 Months",
    referralSource: "Linkedin",
    transferStatus: "Successful",
    transferReceiptUrl: "string",
  },
  {
    id: "4",
    email: "jack@gmail.com",
    firstName: "John",
    lastName: "Doe",
    phoneNumber: "0809845732",
    schoolOrOrganisation: "Next gen hub",
    hasLaptop: true,
    hasProgrammingExperience: true,
    availableHoursPerWeek: 5,
    hasWorkExperience: true,
    cvUrl: "string",
    registrationDate: "2024-10-11T18:07:08.369Z",
    passportUrl: logo,
    motivation: "Career Growth",
    preferredStack: "Software Development",
    duration: "6 Months",
    referralSource: "Linkedin",
    transferStatus: "Successful",
    transferReceiptUrl: "string",
  },
  {
    id: "5",
    email: "jack@gmail.com",
    firstName: "John",
    lastName: "Doe",
    phoneNumber: "0809845732",
    schoolOrOrganisation: "Next gen hub",
    hasLaptop: true,
    hasProgrammingExperience: true,
    availableHoursPerWeek: 5,
    hasWorkExperience: true,
    cvUrl: "string",
    registrationDate: "2024-10-11T18:07:08.369Z",
    passportUrl: logo,
    motivation: "Career Growth",
    preferredStack: "Software Development",
    duration: "6 Months",
    referralSource: "Linkedin",
    transferStatus: "Successful",
    transferReceiptUrl: "string",
  },
  {
    id: "6",
    email: "jack@gmail.com",
    firstName: "John",
    lastName: "Doe",
    phoneNumber: "0809845732",
    schoolOrOrganisation: "Next gen hub",
    hasLaptop: true,
    hasProgrammingExperience: true,
    availableHoursPerWeek: 5,
    hasWorkExperience: true,
    cvUrl: "string",
    registrationDate: "2024-10-11T18:07:08.369Z",
    passportUrl: logo,
    motivation: "Career Growth",
    preferredStack: "Software Development",
    duration: "6 Months",
    referralSource: "Linkedin",
    transferStatus: "Successful",
    transferReceiptUrl: "string",
  },
];
